services:
  postgres:
    image: postgres:18
    container_name: postgres-apsor-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4:9.12
    container_name: pgadmin-apsor-ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "6060:80"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # -------------------------
  # Keycloak DB (separate)
  # -------------------------
  keycloak_postgres:
    image: postgres:18
    container_name: postgres-keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5533:5432"
    networks:
      - backend
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    depends_on:
      - postgres
      - pgadmin

  # -------------------------
  # Keycloak
  # -------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak-apsor-admin
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: "localhost"           # â† Add this
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "127.0.0.1:8443:8080"
    networks:
      - backend
    depends_on:
      - keycloak_postgres
      - pgadmin
      - postgres

  # -------------------------
  # Minio (S3)
  # -------------------------
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio-apsor-s3
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data
    networks:
      - backend
    depends_on:
      - postgres
      - pgadmin
      - keycloak_postgres
      - keycloak

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      mc mb -p local/apsor-media || true;
      # OPTIONAL: make bucket public-read for downloads:
      mc anonymous set download local/apsor-media || true;
      exit 0;
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 3s
      timeout: 2s
      retries: 30

volumes:
  pgdata:
  keycloak_pgdata:
  pgadmin_data:
  minio_data:
  pgdata_test:

networks:
  backend:
    driver: bridge

